console.log("Ali said: Hello")
console.log("Suxrat said: Hi, my name is Shuxrat")
console.log("Ali said: How are you?")
console.log("Shuxrat said: I am good")
console.log("Ali said:I am from Tajikistan, are you from?")
console.log("Shuxrat said: OHhhhh good !!!! I am from Uzbeksitan")
console.log("Ali said: Are you study or work?")
console.log("Shuxrat said: I am study, And you?")
console.log("Ali said: I am businisman")
console.log("Shuxrat said: Tosheknt beutufull sity, is it true ?")
console.log("Ali said: Of course!!!")
console.log("Shuxrat said: Are you first visit in Tashkent?")
console.log("Ali said: Yes,I first visit")
console.log("Shuxrat said: I am sorry, Now will start my lesson. Nice to meet you")
console.log("Ali said: me too, Bay Bay")